sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: zcl201314
  alioss:
    endpoint: oss-cn-shenzhen.aliyuncs.com
    access-key-id: YOUR_ACCESS_KEY_ID
    access-key-secret: YOUR_ACCESS_KEY_SECRET
    bucket-name: sky-take-out-zcl
# access-key-id: YOUR_ACCESS_KEY_ID
# access-key-secret: YOUR_ACCESS_KEY_SECRET
  wechat:
    appid: YOUR_APP_ID
    secret: YOUR_APP_SECRET
# appid: YOUR_APP_ID
# secret: YOUR_APP_SECRET
spring:
  redis:
    host: 192.168.100.128
    port: 6379
    password: zcl201314
    database: 0