server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true
      enabled: true

spring:
  profiles:
    active: dev
  main:
    allow-circular-references: true
  redis:
    host: ${spring.redis.host}
    port: ${spring.redis.port}
    password: ${spring.redis.password}
    database: ${spring.redis.database} #默认使用db0
  datasource:
    # driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sky_take_out?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&allowPublicKeyRetrieval=true
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
    druid:
      # 连接池初始化大小
      initial-size: 5
      # 最小空闲连接数
      min-idle: 5
      # 最大连接数
      max-active: 20
      # 配置检测连接是否有效的 SQL
      validation-query: SELECT 1
      # 申请连接时检测（重要）
      test-on-borrow: true
      # 归还连接时检测
      test-on-return: false
      # 空闲时检测（重要）
      test-while-idle: true
      # 检测间隔时间（毫秒）
      time-between-eviction-runs-millis: 60000
      # 连接最小生存时间（毫秒）
      min-evictable-idle-time-millis: 300000
      # 连接最大生存时间（毫秒），要小于 MySQL 的 wait_timeout
      max-evictable-idle-time-millis: 900000


mybatis:
  #mapper配置文件
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.sky.entity
  configuration:
    #开启驼峰命名
    map-underscore-to-camel-case: true

logging:
  level:
    com:
      sky:
        mapper: debug
        service: info
        controller: info

sky:
  jwt:
    # 设置jwt签名加密时使用的秘钥
    admin-secret-key: itcast
    # 设置jwt过期时间
    admin-ttl: 7200000000
    # 设置前端传递过来的令牌名称
    admin-token-name: token

    user-secret-key: itheima
    user-ttl: 7200000000
    user-token-name: authentication


  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}

  wechat:
    appid: ${sky.wechat.appid}
    appsecret: ${sky.wechat.secret}
#    mchid: ${sky.wechat.mchid}
#    mchSecrialNo: ${sky.wechat.mchSecrialNo}
#    privateKeyPath: ${sky.wechat.privateKeyPath}
#    apiV3Key: ${sky.wechat.apiV3Key}
#    weChatPayCertFilePath: ${sky.wechat.weChatPayCertFilePath}
#    notifyUrl: ${sky.wechat.notifyUrl}
#    refundNotifyUrl: ${sky.wechat.refundNotifyUrl}
  shop:
    address: ${sky.shop.address}
  baidu:
    ak: ${sky.baidu.ak}